Repository almerico/jenkins-x-image, pull requests merged in 2020-02, with the labels that each got.

#3 Update Jenkinsfile
  Jenkinsfile
Labels: autosquash

#11 Update test1
  test1
Labels: automerge

#12 Create test2
  test2
Labels: automerge

#16 Delete test1
  test1
Labels: automerge, updatebot
